# Extracts the 'version' tag from the plugin.yml and stores it in the build.env file
# That file is automatically passed to other dependent tasks
get_version:
  stage: build
  image:
    name: mikefarah/yq:latest
    entrypoint: [""]
  script:
    - export VERSION=$(yq eval '.version' src/main/resources/plugin.yml)
    - echo "VERSION=$VERSION" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - changes: [src/main/resources/plugin.yml]

# Builds the plugin with gradle
# Gradle determines the version of the archive from the same source as `get_version`
# Exports the mcctf-x.y.z.jar file
build_plugin:
  stage: build
  image: eclipse-temurin:17.0.3_7-jdk
  script:
    - ./gradlew shadowJar --no-daemon
  artifacts:
    paths:
      - build/libs/*
  rules:
    - changes: [src/main/resources/plugin.yml]

# Creates a new release and attaches the plugin jar from `build_plugin`
release_plugin:
  stage: deploy
  image: gitlab/glab:latest
  script:
    - echo "Releasing $VERSION"
    - glab auth login --job-token $CI_JOB_TOKEN
    - glab release create $VERSION
    - glab release upload $VERSION build/libs/mcctf-$VERSION.jar --use-package-registry
  needs:
    - job: build_plugin
      artifacts: true
    - job: get_version
      artifacts: true
  rules:
    - changes: [src/main/resources/plugin.yml]